upstream cluster {
    # Instead of default round robin scheduling use least_conn which does not get stalled
    # because of the different times it might take to serve one request.
    least_conn;

    server node0:9000;
    server node1:9000;
    server node2:9000;
    server node3:9000;

    # >= to max amount of concurrency the tests will be running
    keepalive 256;
}

server {
    listen 80;
    server_name node0;

    ignore_invalid_headers off;
    client_max_body_size 0;
    # Disable buffering to allow streaming uploads directly
    proxy_buffering off;
    proxy_request_buffering off;

    location / {
        proxy_pass http://cluster;
        
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        proxy_http_version 1.1;
        proxy_set_header Connection "";
        
        chunked_transfer_encoding off;
        proxy_connect_timeout 300;
        proxy_send_timeout 300s;
        proxy_read_timeout 300s;
    }
}
