CREATE TABLE "report" (
    "id" INT PRIMARY KEY,
    "image" BYTEA, -- arba URL kolkas galima
    "timeAgo" TIMESTAMP, 
    "petName" VARCHAR(63), 
    "status" INT, 
    "location" VARCHAR(63),
    "authorName" VARCHAR(63),
    "authorNickname" VARCHAR(63),
    "type" INT,
    "posted" TIMESTAMP,
    "animalType" VARCHAR(63),
    "pet_id" INT,
    "latitude" DOUBLE PRECISION,
    "longtitude" DOUBLE PRECISION,
    "dominantColors" VARCHAR(63),
    "collarColor" VARCHAR(63),
    "breed" VARCHAR(63),
    "size" VARCHAR(63),
    "gender" VARCHAR(63),
    "tel" VARCHAR(63),
    "email" VARCHAR(63),
    "social" VARCHAR(63),
    "note" VARCHAR(2047)
);